version: '3.7'

services:
    postgres-db:
        restart: always
        image: postgres:latest
        privileged: true
        healthcheck:
            test: [ "CMD", "pg_isready", "-q", "-U", "postgres" ]
            timeout: 45s
            interval: 10s
            retries: 10
        ports:
            - 5432:5432
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            PGDATA: /var/lib/postgresql/data/pgdata
        volumes:
            - ./restaurant_reservation_api/database/postgres/data:/var/lib/postgresql/data/pgdata
        networks:
            restaurant_net:
                aliases:
                    - postgres_net

    api:
        build:
            context: .
            dockerfile: Dockerfile
            target: base
        volumes:
            - '.:/project'
        ports:
            - 5000:5000
        depends_on:
            postgres-db:
                condition: service_healthy
        networks:
            restaurant_net:
                aliases:
                    - api_net

networks:
    restaurant_net:
        driver: bridge
